--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

-- Started on 2022-02-04 18:53:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3320 (class 1262 OID 16400)
-- Name: db_mv; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_mv WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE db_mv OWNER TO postgres;

\connect db_mv

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16401)
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id_departamento integer NOT NULL,
    nm_departamento character varying(100) NOT NULL,
    local character varying(100) NOT NULL
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16406)
-- Name: empregados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empregados (
    id_empregado integer NOT NULL,
    cod_departamento integer,
    cod_emp_funcao integer,
    nm_empregado character varying(100) NOT NULL,
    nm_funcao character varying(100),
    data_admissao date,
    salario numeric(95,5),
    comissao numeric(95,5)
);


ALTER TABLE public.empregados OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16416)
-- Name: empregados_id_empregado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empregados ALTER COLUMN id_empregado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empregados_id_empregado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999
    CACHE 1
);


--
-- TOC entry 3312 (class 0 OID 16401)
-- Dependencies: 209
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (200, 'TI', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (300, 'DP', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (400, 'RH', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (600, 'DELIVERY', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (900, 'DIRETORIA', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (1000, 'FINANCEIRO', 'PORTO ALEGRE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (500, 'EXPEDICAO', 'RECIFE');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (800, 'MANIPULACAO', 'SÃO PAULO');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (700, 'WHATSAPP', 'PARAIBA');
INSERT INTO public.departamentos (id_departamento, nm_departamento, local) VALUES (100, 'CONTABILIDADE', 'PORTO ALEGRE');


--
-- TOC entry 3313 (class 0 OID 16406)
-- Dependencies: 210
-- Data for Name: empregados; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (6, 200, 10, 'MARIA JOSÉ', 'ANALISTA DE SUPORTE', '2015-10-01', 2000.00000, 200.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (7, 200, 10, 'JORDÃO DE SOUZA', 'ANALISTA DE SUPORTE', '2005-08-10', 2000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (8, 300, 20, 'WAGNER RUFINO', 'COORDENADOR', '2000-09-28', 3400.00000, 300.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (9, 300, 20, 'ELAINE MUNIZ', 'COORDENADOR', '2010-05-13', 3500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (10, 400, 30, 'MARCELO SILVA', 'DESENVOLVEDOR JAVA', '2000-05-13', 4500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (11, 400, 30, 'JOTA FERREIRA', 'DESENVOLVEDOR JAVA', '2018-05-13', 4780.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (12, 500, 30, 'LUISA TERRA', 'DESENVOLVEDOR JAVA', '2003-05-13', 4000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (13, 500, 40, 'JULIANA SOUZA', 'DESENVOLVEDOR NODEJS', '2004-05-13', 5300.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (14, 600, 50, 'THIAGO VIEIRA', 'DESENVOLVEDOR JAVASCRIPT', '2009-05-13', 2500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (15, 600, 50, 'DEYVSON FELIX', 'DESENVOLVEDOR JAVASCRIPT', '2010-05-13', 2500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (16, 600, 50, 'DEYVSON SILVA', 'DESENVOLVEDOR JAVASCRIPT', '2007-05-13', 2500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (17, 700, 60, 'MARCELO GOMES', 'GERENTE', '2008-05-13', 8000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (18, 700, 60, 'CLEIBER BEZERRA', 'GERENTE', '2007-05-13', 7000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (19, 700, 60, 'PENELOPE LOPES', 'GERENTE', '2006-05-13', 9500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (20, 800, 70, 'TÂMARA LINA', 'ASSISTENTE', '2005-05-13', 1500.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (21, 800, 70, 'GUMERCINDO PATO', 'ASSISTENTE', '2004-05-13', 1400.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (22, 800, 70, 'MATSUMOTO MOTA', 'ASSISTENTE', '2003-05-13', 1200.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (23, 900, 80, 'FELIPE MARTANI', 'ESPECIALISTA', '2002-05-13', 3000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (24, 900, 80, 'MARCOS SILVA', 'ESPECIALISTA', '2001-05-13', 3000.00000, 500.00000);
INSERT INTO public.empregados (id_empregado, cod_departamento, cod_emp_funcao, nm_empregado, nm_funcao, data_admissao, salario, comissao) VALUES (25, 900, 80, 'IVONETE SILVA', 'ESPECIALISTA', '2000-05-13', 3000.00000, 500.00000);


--
-- TOC entry 3321 (class 0 OID 0)
-- Dependencies: 211
-- Name: empregados_id_empregado_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empregados_id_empregado_seq', 31, true);


--
-- TOC entry 3169 (class 2606 OID 16405)
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id_departamento);


--
-- TOC entry 3171 (class 2606 OID 16410)
-- Name: empregados empregados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empregados
    ADD CONSTRAINT empregados_pkey PRIMARY KEY (id_empregado);


--
-- TOC entry 3172 (class 2606 OID 16411)
-- Name: empregados empregados_cod_departamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empregados
    ADD CONSTRAINT empregados_cod_departamento_fkey FOREIGN KEY (cod_departamento) REFERENCES public.departamentos(id_departamento);


-- Completed on 2022-02-04 18:53:19

--
-- PostgreSQL database dump complete
--

